### PR TITLE
Arrow functions for Javascript

### PR DESCRIPTION
**Pull request by adelarsq**
Support for Javascript arrow function (=>).

### CODE REVIEW

**Comment by calebsmith** [comment]
Nice idea!

I think the merge conflict is likely some silly issue with some recent changes to master. Probably just the README. Would appreciate a quick merge of master into your fork to resolve it.

Otherwise looks good. If you don't get around to that soon I'll just merge it in and get it sorted.

Thanks for the work!

**Comment by adelarsq** [comment]
Strange that I used the last branch. I will create a new request today or tomorrow I think.

**Comment by calebsmith** [comment]
No worries! Thanks. I would've tried it myself but sort of forgot. I suppose it isn't a *major* *major* feature.

Thank you, and I'll try to get to it over the weekend if you don't.

**Comment by adelarsq** [comment]
I did a new request, so I'm closing this.

**Pull request closed without merging**
